integrations:
  rescuetime:
    frequency: "daily"
    overview: true
    top-categories: true
    top-activities: false
  last-fm:
    frequency: "daily"
    all: true
  pocket-casts:
    frequency: "daily"
    all: true
  wakatime:
    frequency: "daily"
    all: true
  google-fit:
    frequency: "daily"
    all: true
  oura-ring:
    frequency: "daily"
    all: true
  twitter:
    frequency: "daily"
    all: true
  # clockify:
  # spotify:
  # goodreads:
