name: Node CI
on:
  push:
    branches: [master]
jobs:
  release:
    name: Build
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: ":rocket: Deploy new library version"
          commit_user_name: Finding Anand
          commit_user_email: bot@anandchowdhary.com
          commit_author: Finding Anand <bot@anandchowdhary.com>
      - name: Build static site
        run: cd src/app && npm ci && npm run export
      - name: Deploy site to GitHub Pages
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: "src/app/__sapper__/export/life/"
          GH_PAT: ${{ secrets.GH_PAT }}
